"""アプリ全体の定数・初期データ・エイリアスオーバーライド。"""
from __future__ import annotations

# ── ステータス / カテゴリ選択肢 ──────────────────────────────────────────────

STATUS_CHOICES: list[str] = [
    "未掲載",
    "交渉中",
    "レス待ち",
    "掲載中",
    "掲載不可",
]
DEFAULT_STATUS = "未掲載"

# ── client_media_status の値フィールド（status + 4 詳細 + memo） ───────────────
# memo は AI 更新で touch しない「ユーザー保護領域」
CMS_VALUE_FIELDS: list[str] = [
    "status",
    "monthly_conversions",   # 掲載中: 月間獲得件数
    "reward_terms",          # 掲載中: 経済条件 (報酬率・条件)
    "negotiation_status",    # 交渉中 / レス待ち: 交渉ステータス
    "ineligible_reason",     # 掲載不可: 掲載不可理由
    "memo",                  # ユーザー自由記述（AI 上書き禁止）
]

# UI で見せる日本語ラベル
CMS_FIELD_LABELS: dict[str, str] = {
    "status":              "ステータス",
    "monthly_conversions": "月間獲得件数",
    "reward_terms":        "経済条件 (報酬率・条件)",
    "negotiation_status":  "交渉ステータス",
    "ineligible_reason":   "掲載不可理由",
    "memo":                "メモ（自由記述・AI 更新で保護）",
}

CATEGORY_CHOICES: list[str] = [
    "主要還元系",
    "初期月額・DG",
    "イレギュラー媒体",
    "新規媒体",
    "その他",
]

STRATEGY_COLUMNS: list[str] = [
    "date",
    "advertiser_name",
    "topic_summary",
    "focus_theme",
    "pending_issue",
    "base_commission",
    "negotiable_commission",
]

# display / upsert で使う列（aliases と is_active は別管理）
MEDIA_MASTER_COLUMNS: list[str] = [
    "sid",
    "site_name",
    "site_url",
    "media_contact",
    "category",
]

# ── 媒体マスター初期シード（67媒体） ─────────────────────────────────────────

INITIAL_MEDIA: list[dict] = [
    # ── 主要還元系 ──────────────────────────────────────────────────────────
    {"sid": "2560803", "site_name": "モッピーEC（定率）【LS】",
     "site_url": "http://pc.moppy.jp/",                              "media_contact": "山田 基道",         "category": "主要還元系"},
    {"sid": "2034638", "site_name": "ハピタス",
     "site_url": "http://hapitas.jp/",                               "media_contact": "北川 紗子",         "category": "主要還元系"},
    {"sid": "1847069", "site_name": "Point Income【LS】",
     "site_url": "http://pointi.jp/",                                "media_contact": "山田 基道",         "category": "主要還元系"},
    {"sid": "1409889", "site_name": "ニフティポイントクラブ",
     "site_url": "http://lifemedia.jp/",                             "media_contact": "山田 基道",         "category": "主要還元系"},
    {"sid": "3654442", "site_name": "Powl【LS】",
     "site_url": "https://static.powl.jp/lp/",                      "media_contact": "山田 基道",         "category": "主要還元系"},
    {"sid": "1424679", "site_name": "ECナビ（物販アカウント）（JIPC加盟企業）",
     "site_url": "https://ecnavi.jp/",                               "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "1118227", "site_name": "MPC-ちょびリッチドットコム",
     "site_url": "http://www.chobirich.com",                         "media_contact": "北川 紗子",         "category": "主要還元系"},
    {"sid": "1725097", "site_name": "ポイントタウン（JIPC参加企業）",
     "site_url": "http://www.pointtown.com/",                        "media_contact": "北川 紗子",         "category": "主要還元系"},
    {"sid": "1294285", "site_name": "ワラウ",
     "site_url": "http://www.warau.jp/",                             "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "3571617", "site_name": "Vポイントモール",
     "site_url": "https://t-mall.tsite.jp",                          "media_contact": "北川 紗子",         "category": "主要還元系"},
    {"sid": "2223245", "site_name": "ベネフィット・ステーション",
     "site_url": "https://bs.benefit-one.inc/",                      "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "3333305", "site_name": "みんなの得トクひろば",
     "site_url": "https://tokutoku-park.chuden.jp/",                 "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "1422896", "site_name": "イーウェル【WELBOX】",
     "site_url": "http://www.welbox.com/",                           "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "3919659", "site_name": "ONE",
     "site_url": "http://wow.one/app",                               "media_contact": "山田 基道",         "category": "主要還元系"},
    {"sid": "3897831", "site_name": "SKYFLAG",
     "site_url": "https://skyflag.info/",                            "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "1686792", "site_name": "すぐたま（旧ネットマイル）",
     "site_url": "http://www.sugutama.jp/",                          "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "1873016", "site_name": "げん玉",
     "site_url": "http://www.gendama.jp/",                           "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "1029920", "site_name": "GetMoney!（JIPC参加企業）",
     "site_url": "http://www.dietnavi.com",                          "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "3204591", "site_name": "Pontaボーナスパーク",
     "site_url": "https://www.bonuspark.jp/",                        "media_contact": "山田 基道",         "category": "主要還元系"},
    {"sid": "4190377", "site_name": "クラシルリテールネットワーク",
     "site_url": "https://www.rewards.kurashiru.com/",               "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "3622914", "site_name": "MileagePlus Shopping",
     "site_url": "https://globalshopping.mileageplus.com/jp/",       "media_contact": "趙 彗允",           "category": "主要還元系"},
    {"sid": "2016482", "site_name": "えんためねっと",
     "site_url": "http://www.yentame.net/",                          "media_contact": "システム管理者（PMO）", "category": "主要還元系"},
    {"sid": "3457932", "site_name": "dポイント広場",
     "site_url": "https://hiroba.dpoint.jp/",                        "media_contact": "北川 紗子",         "category": "主要還元系"},
    {"sid": "4171006", "site_name": "PLUG【LS】",
     "site_url": "https://lp.plugapp.jp/",                           "media_contact": "山田 基道",         "category": "主要還元系"},
    {"sid": "3243972", "site_name": "FMVキャッシュバックモール",
     "site_url": "https://azby.fmworld.net/app/customer/premium/ViewTop.act",
                                                                      "media_contact": "趙 彗允",           "category": "主要還元系"},
    # ── 初期月額・DG ─────────────────────────────────────────────────────────
    {"sid": "3215048", "site_name": "Rebates（リーベイツ）",
     "site_url": "https://www.rebates.jp/",                          "media_contact": "晝間 圭太",         "category": "初期月額・DG"},
    {"sid": "3371703", "site_name": "LINEブランドカタログ（旧：LINE ショッピング）",
     "site_url": "https://line.me/ja/",                              "media_contact": "北川 紗子",         "category": "初期月額・DG"},
    {"sid": "1837919", "site_name": "セゾンポイントモール",
     "site_url": "http://www.a-q-f.com/index.html",                  "media_contact": "山田 基道",         "category": "初期月額・DG"},
    {"sid": "1805522", "site_name": "ANAマイレージモール",
     "site_url": "http://www.ana.co.jp/amc/reference/tameru/mileagemall/",
                                                                      "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "1254586", "site_name": "日本航空-JMBモール",
     "site_url": "https://partner.jal.co.jp/jmm/",                  "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3921458", "site_name": "J-POINTモール",
     "site_url": "https://www.okidokiland.com/",                     "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "2638735", "site_name": "EPOSポイントUPサイト（旧:たまるマーケット）",
     "site_url": "http://tamaru.eposcard.co.jp/",                    "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "2633282", "site_name": "L三井住友ｶｰﾄﾞPUM（定率）",
     "site_url": "https://www.smbc-card.com/pointup/",               "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3873252", "site_name": "dカード ポイントモール",
     "site_url": "https://docomo.pointupmall.com/",                  "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3903207", "site_name": "POINT名人.com",
     "site_url": "https://www.pointmall.cr.mufg.jp/",                "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3614468", "site_name": "VIEWショッピングステーション",
     "site_url": "https://www.viewshoppingstation.com",              "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "1947025", "site_name": "オリコモール",
     "site_url": "http://www.oricomall.com/",                        "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3258924", "site_name": "ポイントアップマーケットWEB",
     "site_url": "https://www.ts3pum.com/",                          "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3249966", "site_name": "TOKYU POINT モール",
     "site_url": "http://www.topcard.co.jp/mall/",                   "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "1976350", "site_name": "ジャックス",
     "site_url": "http://www.jaccs.co.jp",                           "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "2879506", "site_name": "UCSぽいん貯モール",
     "site_url": "http://poincho.ucscard.co.jp/",                    "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "2711027", "site_name": "ダイナースクラブ オンラインショッピングモール",
     "site_url": "http://www.dnonlinemall.jp/",                      "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "2262541", "site_name": "L-Mall（ライフカード）",
     "site_url": "http://lmall.jp/",                                 "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3345628", "site_name": "POCKET MALL",
     "site_url": "http://pml.pocketcard.co.jp/",                     "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3477032", "site_name": "JRキューポ ポイントモール",
     "site_url": "http://www.garage.co.jp/ja/company/",              "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "2711031", "site_name": "オンラインショッピングモール（三井住友トラストクラブ）",
     "site_url": "http://www.sumitclubonlinemall.jp/",               "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "4310307", "site_name": "メルペイモール",
     "site_url": "https://www.garage.co.jp/",                        "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3926496", "site_name": "【上位層】J-POINTモール",
     "site_url": "https://www.okidokiland.com/shop_list/high_rank/", "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3877463", "site_name": "【上位層】dカード ポイントモール",
     "site_url": "https://docomo.pointupmall.com/",                  "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "4433291", "site_name": "【上位層】EPOSポイントUPサイト",
     "site_url": "https://tamaru.eposcard.co.jp/",                   "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    {"sid": "3405537", "site_name": "三井住友カードPUM（プレミアム）",
     "site_url": "http://pointupmall.com/",                          "media_contact": "趙 彗允",           "category": "初期月額・DG"},
    # ── イレギュラー媒体 ────────────────────────────────────────────────────
    {"sid": "3677410", "site_name": "CPV-Retargeting",
     "site_url": "https://corp.intimatemerger.com/",                 "media_contact": "大山 美沙希",       "category": "イレギュラー媒体"},
    {"sid": "3278892", "site_name": "SAKIDORI",
     "site_url": "http://sakidori.co/",                              "media_contact": "吉田 遼功",         "category": "イレギュラー媒体"},
    {"sid": "3532319", "site_name": "mybest",
     "site_url": "https://my-best.com",                              "media_contact": "吉田 遼功",         "category": "イレギュラー媒体"},
    {"sid": "3379024", "site_name": "Simeji",
     "site_url": "https://simeji.me/",                               "media_contact": "吉田 遼功",         "category": "イレギュラー媒体"},
    {"sid": "4165306", "site_name": "Skimlinks",
     "site_url": "https://skimlinks.com/",                           "media_contact": "大山 美沙希",       "category": "イレギュラー媒体"},
    # ── 新規媒体 ─────────────────────────────────────────────────────────────
    {"sid": "4354236", "site_name": "クラシル比較",
     "site_url": "https://hikaku.kurashiru.com/",                    "media_contact": "川井 悠史",         "category": "新規媒体"},
    {"sid": "4297578", "site_name": "バンドルカード ボーナスタウン",
     "site_url": "https://vandle.jp/",                              "media_contact": "趙 彗允",           "category": "新規媒体"},
    {"sid": "4170352", "site_name": "dポイントマーケット",
     "site_url": "https://dmarket.docomo.ne.jp/",                    "media_contact": "晝間 圭太",         "category": "新規媒体"},
    {"sid": "4365090", "site_name": "BANKITミニアプリ「データの貯金箱」",
     "site_url": "https://www.bankit.jp/miniapp/",                   "media_contact": "山田 基道",         "category": "新規媒体"},
    {"sid": "4355022", "site_name": "DDuetコインモール【LS】",
     "site_url": "https://dduetcoinmall.duskin.jp",                  "media_contact": "北川 紗子",         "category": "新規媒体"},
    {"sid": "4252737", "site_name": "タウンWiFi",
     "site_url": "https://apps.apple.com/jp/app/id988737164",        "media_contact": "山田 基道",         "category": "新規媒体"},
    {"sid": "4216249", "site_name": "楽天ウェブ検索",
     "site_url": "https://websearch.rakuten.co.jp/SimpleTop",        "media_contact": "晝間 圭太",         "category": "新規媒体"},
    {"sid": "4306314", "site_name": "DMMポイントクラブ",
     "site_url": "https://www.pointclub.dmm.com/",                   "media_contact": "山田 基道",         "category": "新規媒体"},
    {"sid": "3773117", "site_name": "トリマ",
     "site_url": "https://www.trip-mile.com/",                       "media_contact": "山田 基道",         "category": "新規媒体"},
    {"sid": "4497079", "site_name": "イオンカードポイントモール",
     "site_url": "https://pointmall.aeon.co.jp/",                    "media_contact": "趙 彗允",           "category": "新規媒体"},
    {"sid": "4481637", "site_name": "KABU&カブ活",
     "site_url": "https://kabukatsu.x-kabuand.com/",                 "media_contact": "趙 彗允",           "category": "新規媒体"},
]

# ── エイリアスオーバーライド（SID → 追加エイリアスリスト） ──────────────────
# ※ normalize.py が自動生成するエイリアスに加えて手動で追加したいものを書く

ALIAS_OVERRIDES: dict[str, list[str]] = {
    "1805522": ["ana", "全日空", "anaマイレージ", "anaマイル"],
    "1254586": ["jal", "jmb", "jalマイル", "日本航空"],
    "3371703": ["line", "lineショッピング", "lineブランド", "ライン"],
    "1837919": ["セゾン", "セゾンポイント", "永久不滅", "saison"],
    "2638735": ["エポス", "epos", "たまるマーケット", "エポスポイント"],
    "3215048": ["rebates", "リーベイツ", "楽天リーベイツ"],
    "1424679": ["ecナビ", "ecnavi"],
    "3571617": ["vポイントモール", "t-mall", "tmall", "tポイント"],
    "2034638": ["ハピタス", "hapitas"],
    "2560803": ["モッピー", "moppy"],
    "3873252": ["dカード", "dcard", "dポイントモール"],
    "2262541": ["l-mall", "lmall", "ライフカード", "エルモール"],
    "3457932": ["dポイント広場"],
    "4170352": ["dポイントマーケット"],
    "1847069": ["ポイントインカム", "point income"],
    "1409889": ["ライフメディア", "ニフティ"],
    "1118227": ["ちょびリッチ"],
    "1725097": ["ポイントタウン"],
    "1873016": ["gendama"],
    "1029920": ["getmoney", "ダイエットナビ"],
    "3204591": ["ポンタ", "ponta", "ボーナスパーク"],
    "3921458": ["ジェイポイント", "j-point", "okidoki"],
    "2633282": ["三井住友", "smbc"],
    "3903207": ["point名人", "mufg", "三菱ufj"],
    "3614468": ["view", "ビュースイカ", "jre"],
    "1947025": ["オリコ", "orico"],
    "3249966": ["東急ポイント", "tokyu"],
    "2879506": ["ucs", "ucsカード"],
    "2711027": ["ダイナース", "diners"],
    "3345628": ["ポケットモール"],
    "3477032": ["jrキューポ", "jrq"],
    "4310307": ["メルペイ", "merpay"],
    "2016482": ["えんためねっと", "yentame"],
    "3622914": ["mileageplus", "ユナイテッド"],
    "4190377": ["クラシル", "kurashiru"],
    "2223245": ["ベネフィット", "benefit"],
    "3654442": ["powl"],
    "4171006": ["plug"],
    "3919659": ["one", "wow"],
    "3897831": ["skyflag"],
    "1686792": ["すぐたま", "ネットマイル"],
    "1294285": ["ワラウ", "warau"],
    "4354236": ["クラシル比較"],
    "4297578": ["バンドルカード", "vandle"],
    "4365090": ["bankit", "データの貯金箱"],
    "4355022": ["dduet", "ダスキン"],
    "4252737": ["タウンwifi"],
    "4216249": ["楽天検索"],
    "4306314": ["dmm", "dmmポイント"],
    "3773117": ["トリマ"],
    "4497079": ["イオンカード", "aeon"],
    "4481637": ["kabu", "カブ活"],
    "3278892": ["sakidori"],
    "3532319": ["mybest", "マイベスト"],
    "3379024": ["simeji", "シメジ"],
    "4165306": ["skimlinks"],
    "3243972": ["fmv", "富士通"],
    "3405537": ["三井住友プレミアム"],
    "3926496": ["上位層jpoint"],
    "3877463": ["上位層dカード"],
    "4433291": ["上位層エポス"],
}
